apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cheese
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: stilton.kubernetes.mesos
    http:
      paths:
      - path: /
        backend:
          serviceName: stilton
          servicePort: http
  - host: www.k8sdcos-cheddar.com
    http:
      paths:
      - path: /
        backend:
          serviceName: cheddar
          servicePort: http
  - host: wensleydale.kubernetes.mesos
    http:
      paths:
      - path: /
        backend:
          serviceName: wensleydale
          servicePort: http
